<?xml version="1.0" encoding="utf-8"?><Database Name="BasesLoaded" Class="LINQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=safdftsa6b.database.windows.net;Initial Catalog=BasesLoaded;User ID=mssateam01;Connect Timeout=60" SettingsObjectName="OpeningPitch.Properties.Settings" SettingsPropertyName="BasesLoadedConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zipcode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AltPosition1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AltPosition2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TeamName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Approved" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Activated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Team_Player" Member="Team" ThisKey="TID" OtherKey="TID" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="TID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CoachFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CoachLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Team_Player" Member="Players" ThisKey="TID" OtherKey="TID" Type="Player" />
    </Type>
  </Table>
</Database>